version: '3.9'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: zenn-docs
    image: zenn-docs
    volumes:
      - type: bind
        source: "."
        target: "/workspaces/zenn-docs"
        consistency: "cached"
