name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run oven-sh/setup-bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: Run bun install
        run: bun install --no-save
      - name: Run bun lint
        run: bun lint
